version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
      
  web:
    build: .
    environment:
      url: postgres://postgres:root@postgres:5432/postgres
    command: python run.py
    ports:
      - "8080:8080"
    links:
      - postgres
